services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: